In [13]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency

In [14]:
data = pd.read_pickle('RFM анализ таблица.pkl')
data

,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_Score_sum,RFM_Score_str,Segment
CustomerID,,,,,,,,,
12346.0,326,1,77183.60,1,1,5,7,115,Other
12347.0,2,7,4310.00,5,5,5,15,555,Champion
12348.0,75,4,1797.24,2,4,4,10,244,At Risk
12349.0,19,1,1757.55,4,1,4,9,414,New
12350.0,310,1,334.40,1,1,2,4,112,Lost
...,...,...,...,...,...,...,...,...,...
18280.0,278,1,180.60,1,2,1,4,121,Lost
18281.0,181,1,80.82,1,2,1,4,121,Lost
18282.0,8,2,178.05,5,3,1,9,531,Other
18283.0,4,16,2045.53,5,5,4,14,554,Other
18287.0,43,3,1837.28,3,4,4,11,344,Loyal

In [15]:
data_atrisk = data[data['Segment'] == 'At Risk']
data_atrisk

,Recency,Frequency,Monetary,R_score,F_score,M_score,RFM_Score_sum,RFM_Score_str,Segment
CustomerID,,,,,,,,,
12348.0,75,4,1797.24,2,4,4,10,244,At Risk
12383.0,185,5,1850.56,1,4,4,9,144,At Risk
12399.0,119,4,1108.65,2,4,4,10,244,At Risk
12455.0,73,6,2466.86,2,4,5,11,245,At Risk
12502.0,96,5,3723.87,2,4,5,11,245,At Risk
...,...,...,...,...,...,...,...,...,...
18178.0,129,4,1590.81,2,4,4,10,244,At Risk
18202.0,200,3,1396.99,1,4,4,9,144,At Risk
18231.0,192,5,2071.77,1,4,5,10,145,At Risk
18239.0,219,5,1561.61,1,4,4,9,144,At Risk
18260.0,173,6,2628.35,2,5,5,12,255,At Risk

In [16]:
np.random.seed(51)
np.random.choice(['A','B'], size=84)
group_A = np.random.binomial(1,0.1, size= 84)
group_B = np.random.binomial(1,0.15, size= 84)

In [17]:
group_A.sum()

np.int64(5)

In [18]:
group_B.sum()

np.int64(16)

In [19]:
table = [[5,79],
         [16,68]]
chi2 ,p_value , dof, expected = chi2_contingency(table)
print('p-value', p_value)

p-value 0.01965615725016987